# Generated by Django 5.2.12 on 2026-04-24 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='student_signup_data',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('st_name', models.CharField()),
                ('st_email', models.EmailField(max_length=254)),
                ('st_username', models.CharField()),
                ('st_password', models.CharField()),
                ('st_confirm_pass', models.CharField()),
            ],
        ),
    ]
