# Generated by Django 5.2.12 on 2026-04-30 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('edu', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Subjects_details',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_name', models.CharField()),
                ('course_desc', models.CharField()),
                ('no_of_students', models.IntegerField()),
                ('months', models.IntegerField()),
                ('Rating', models.IntegerField()),
                ('price', models.CharField()),
            ],
        ),
    ]
