# Generated by Django 5.2.12 on 2026-06-16 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('edu', '0003_student_signup_data_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='enrollment_data',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField()),
                ('last_name', models.CharField()),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField()),
                ('dob', models.CharField()),
                ('gender', models.CharField()),
                ('current_class', models.IntegerField()),
                ('school', models.CharField()),
                ('course', models.CharField()),
                ('parent_name', models.CharField()),
                ('parent_phone', models.CharField()),
                ('address', models.CharField()),
                ('message', models.CharField()),
            ],
        ),
    ]
