# Generated by Django 5.2.12 on 2026-06-19 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('edu', '0004_enrollment_data'),
    ]

    operations = [
        migrations.CreateModel(
            name='Curriculum_data',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject_name', models.CharField()),
                ('subject_desc', models.CharField()),
                ('skills', models.CharField()),
                ('skills_desc', models.CharField()),
                ('curriculum_module_headings', models.CharField()),
                ('curriculum_topic_names', models.CharField()),
            ],
        ),
    ]
