# Generated by Django 5.2.12 on 2026-06-20 06:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('edu', '0005_curriculum_data'),
    ]

    operations = [
        migrations.CreateModel(
            name='curriculum_module_heading',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('curriculum_module_heading', models.CharField()),
            ],
        ),
        migrations.CreateModel(
            name='curriculum_topic_name',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('curriculum_topic_names', models.CharField()),
            ],
        ),
        migrations.CreateModel(
            name='skills_n_learnings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('skill', models.CharField()),
                ('skill_desc', models.CharField()),
            ],
        ),
        migrations.RemoveField(
            model_name='curriculum_data',
            name='curriculum_module_headings',
        ),
        migrations.RemoveField(
            model_name='curriculum_data',
            name='curriculum_topic_names',
        ),
        migrations.RemoveField(
            model_name='curriculum_data',
            name='skills',
        ),
        migrations.RemoveField(
            model_name='curriculum_data',
            name='skills_desc',
        ),
    ]
