# Generated by Django 5.2.12 on 2026-06-20 06:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('edu', '0006_curriculum_module_heading_curriculum_topic_name_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='curriculum_module_heading',
        ),
        migrations.DeleteModel(
            name='skills_n_learnings',
        ),
    ]
