# Generated by Django 5.2.12 on 2026-06-21 04:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('edu', '0007_delete_curriculum_module_heading_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='curriculum_topic_videos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('v', models.CharField()),
            ],
        ),
    ]
