# Generated by Django 5.2.12 on 2026-06-22 15:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('edu', '0009_course_module_topic_delete_curriculum_data_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='concepts_covered',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('conc_cov', models.CharField(max_length=200)),
                ('concept_desc', models.TextField()),
                ('order', models.PositiveIntegerField(default=0)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='concepts_covered', to='edu.course')),
            ],
        ),
    ]
