# Generated by Django 5.2.12 on 2026-06-23 12:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('edu', '0011_enrollment_data_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='enrollment_data',
            name='user',
        ),
    ]
