# Generated by Django 5.2.12 on 2026-06-24 05:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('edu', '0013_enrollment_data_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='enrollment_data',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='enrollments', to='edu.course'),
        ),
    ]
