# Generated by Django 5.2.12 on 2026-06-24 05:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('edu', '0014_alter_enrollment_data_course'),
    ]

    operations = [
        migrations.AlterField(
            model_name='enrollment_data',
            name='course',
            field=models.CharField(),
        ),
    ]
