# Generated by Django 5.2.12 on 2026-06-25 09:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('edu', '0015_alter_enrollment_data_course'),
    ]

    operations = [
        migrations.CreateModel(
            name='user_n_course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(max_length=200)),
                ('course', models.CharField(max_length=200)),
            ],
        ),
    ]
