# Generated by Django 5.2.12 on 2026-06-25 11:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('edu', '0017_alter_user_n_course_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user_n_course',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_n_course', to='edu.course'),
        ),
    ]
