# Generated by Django 5.2.12 on 2026-07-01 06:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('edu', '0018_alter_user_n_course_course'),
    ]

    operations = [
        migrations.CreateModel(
            name='topic_links',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.CharField()),
                ('topic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='topics_links', to='edu.topic')),
            ],
        ),
    ]
