# Generated by Django 5.2.12 on 2026-07-07 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('edu', '0020_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='original_price',
            field=models.DecimalField(decimal_places=2, default=3999, max_digits=8),
        ),
        migrations.AddField(
            model_name='course',
            name='price',
            field=models.DecimalField(decimal_places=2, default=5000, max_digits=8),
        ),
    ]
