# Generated by Django 5.2.12 on 2026-07-09 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('edu', '0021_course_original_price_course_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='topic_links',
            name='is_free',
            field=models.BooleanField(default=False),
        ),
    ]
