# Generated by Django 5.2.12 on 2026-07-28 15:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('edu', '0025_update_photo'),
    ]

    operations = [
        migrations.DeleteModel(
            name='update_photo',
        ),
    ]
