# Generated by Django 5.2.12 on 2026-07-28 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('edu', '0026_delete_update_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendance',
            name='present',
            field=models.CharField(default='day', max_length=10),
        ),
    ]
