# Generated by Django 5.2.12 on 2026-07-31 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('edu', '0028_update_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='update_photo',
            name='rm_photo',
            field=models.BooleanField(default=False),
        ),
    ]
